 hosts: terraform-ansible
  tasks:
    - name: instalando python3
      apt:
       pkg:
        - python3
        - virtualenv
      update_cache: yes
      become: yes
    - name: dependencias no venv
      pip:
       virtualenv: /home/ubuntu/tcc/venv
       name:
        - django
        - djangorestframework