FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy project for image
COPY ./AppRazor ./AppRazor/
RUN cd ./AppRazor

# Build
RUN cd ./AppRazor && dotnet build && dotnet restore ./AppRazor.csproj && dotnet publish -c Release -o out

RUN ls -a && pwd && cd ./AppRazor && ls -a

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS runtime
WORKDIR /app
COPY --from=build-env /app/AppRazor/out ./

EXPOSE 8080
CMD ["dotnet", "AppRazor.dll"]
