FROM ubuntu:latest
WORKDIR /app
ARG PORT=3000
ENV PORT=$PORT
EXPOSE $PORT
RUN apt-get update && apt-get install -y aspnetcore-runtime-6.0
COPY ./Alura-Devops/AppRazor AppRazor
RUN chmod +x ./AppRazor
ENTRYPOINT ["dotnet", "AppRazor"]
