FROM ubuntu:latest
WORKDIR /app
ARG PORT=3000
ENV PORT=$PORT
EXPOSE $PORT
RUN apt-get update && \
    apt-get install -y dotnet-sdk-6.0 && \ 
    apt-get install -y dotnet-runtime-6.0
COPY ./Alura-Devops/AppRazor AppRazor
RUN chmod +x ./AppRazor
RUN dotnet restore "./AppRazor/AppRazor.csproj"
RUN dotnet publish "./AppRazor/AppRazor.csproj"
RUN ls -a
CMD ["dotnet", "./AppRazor"]
