name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
    # Artifact name
        name: program on dotnet
    
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.USERNAME_DOCKER_HUB }}
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.0.0
      with:
        context: .
        file: ./Alura-Devops/Docker/dockerfile
        push: true
        tags: ${{ secrets.USERNAME_DOCKER_HUB }}/apprazor:${{github.ref_name}}
