name: dotnet-build

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - './**.cs'
    - './**.csproj'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    env:
      DOTNET_VERSION: '6.0'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3

    - name: Set up DotNet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: cd ./Alura-Devops/AppRazor && dotnet restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: dotnet build --configuration Release --no-restore


  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit
